/**
 * Embedded airport directory for the UI's type-ahead. A curated set of ~230
 * major international airports — enough for useful autocomplete without a
 * network dependency. Each entry: IATA code, primary city, airport name, country.
 *
 * searchAirports() ranks matches: exact IATA, then IATA prefix, then city, then
 * name/country — so typing "lon", "lhr", or "heath" all surface London Heathrow.
 */

export interface Airport {
  iata: string;
  city: string;
  name: string;
  country: string;
}

// [iata, city, name, country]
const RAW: Array<[string, string, string, string]> = [
  // North America — USA
  ["ATL", "Atlanta", "Hartsfield–Jackson Atlanta Intl", "USA"],
  ["LAX", "Los Angeles", "Los Angeles Intl", "USA"],
  ["ORD", "Chicago", "O'Hare Intl", "USA"],
  ["DFW", "Dallas", "Dallas/Fort Worth Intl", "USA"],
  ["DEN", "Denver", "Denver Intl", "USA"],
  ["JFK", "New York", "John F. Kennedy Intl", "USA"],
  ["EWR", "Newark", "Newark Liberty Intl", "USA"],
  ["LGA", "New York", "LaGuardia", "USA"],
  ["SFO", "San Francisco", "San Francisco Intl", "USA"],
  ["OAK", "Oakland", "Oakland Intl", "USA"],
  ["SJC", "San Jose", "San Jose Intl", "USA"],
  ["SEA", "Seattle", "Seattle–Tacoma Intl", "USA"],
  ["LAS", "Las Vegas", "Harry Reid Intl", "USA"],
  ["MCO", "Orlando", "Orlando Intl", "USA"],
  ["MIA", "Miami", "Miami Intl", "USA"],
  ["FLL", "Fort Lauderdale", "Fort Lauderdale–Hollywood Intl", "USA"],
  ["PHX", "Phoenix", "Phoenix Sky Harbor Intl", "USA"],
  ["IAH", "Houston", "George Bush Intercontinental", "USA"],
  ["HOU", "Houston", "William P. Hobby", "USA"],
  ["BOS", "Boston", "Logan Intl", "USA"],
  ["MSP", "Minneapolis", "Minneapolis–Saint Paul Intl", "USA"],
  ["DTW", "Detroit", "Detroit Metropolitan", "USA"],
  ["PHL", "Philadelphia", "Philadelphia Intl", "USA"],
  ["CLT", "Charlotte", "Charlotte Douglas Intl", "USA"],
  ["BWI", "Baltimore", "Baltimore/Washington Intl", "USA"],
  ["DCA", "Washington", "Ronald Reagan National", "USA"],
  ["IAD", "Washington", "Dulles Intl", "USA"],
  ["SLC", "Salt Lake City", "Salt Lake City Intl", "USA"],
  ["SAN", "San Diego", "San Diego Intl", "USA"],
  ["TPA", "Tampa", "Tampa Intl", "USA"],
  ["PDX", "Portland", "Portland Intl", "USA"],
  ["HNL", "Honolulu", "Daniel K. Inouye Intl", "USA"],
  ["AUS", "Austin", "Austin–Bergstrom Intl", "USA"],
  ["MDW", "Chicago", "Chicago Midway", "USA"],
  ["BNA", "Nashville", "Nashville Intl", "USA"],
  ["RDU", "Raleigh", "Raleigh–Durham Intl", "USA"],
  ["SMF", "Sacramento", "Sacramento Intl", "USA"],
  ["SNA", "Santa Ana", "John Wayne", "USA"],
  ["DAL", "Dallas", "Dallas Love Field", "USA"],
  ["STL", "St. Louis", "St. Louis Lambert Intl", "USA"],
  ["MCI", "Kansas City", "Kansas City Intl", "USA"],
  ["CLE", "Cleveland", "Cleveland Hopkins Intl", "USA"],
  ["PIT", "Pittsburgh", "Pittsburgh Intl", "USA"],
  ["CVG", "Cincinnati", "Cincinnati/Northern Kentucky Intl", "USA"],
  ["IND", "Indianapolis", "Indianapolis Intl", "USA"],
  ["CMH", "Columbus", "John Glenn Columbus Intl", "USA"],
  ["MKE", "Milwaukee", "Milwaukee Mitchell Intl", "USA"],
  ["ONT", "Ontario", "Ontario Intl", "USA"],
  ["BUR", "Burbank", "Hollywood Burbank", "USA"],
  ["ABQ", "Albuquerque", "Albuquerque Intl Sunport", "USA"],
  ["ANC", "Anchorage", "Ted Stevens Anchorage Intl", "USA"],
  ["BUF", "Buffalo", "Buffalo Niagara Intl", "USA"],
  ["JAX", "Jacksonville", "Jacksonville Intl", "USA"],
  ["RSW", "Fort Myers", "Southwest Florida Intl", "USA"],
  ["PBI", "West Palm Beach", "Palm Beach Intl", "USA"],
  // Canada
  ["YYZ", "Toronto", "Toronto Pearson Intl", "Canada"],
  ["YVR", "Vancouver", "Vancouver Intl", "Canada"],
  ["YUL", "Montreal", "Montréal–Trudeau Intl", "Canada"],
  ["YYC", "Calgary", "Calgary Intl", "Canada"],
  ["YEG", "Edmonton", "Edmonton Intl", "Canada"],
  ["YOW", "Ottawa", "Ottawa Macdonald–Cartier Intl", "Canada"],
  ["YWG", "Winnipeg", "Winnipeg Richardson Intl", "Canada"],
  ["YHZ", "Halifax", "Halifax Stanfield Intl", "Canada"],
  // Mexico / Central America / Caribbean
  ["MEX", "Mexico City", "Mexico City Intl", "Mexico"],
  ["CUN", "Cancún", "Cancún Intl", "Mexico"],
  ["GDL", "Guadalajara", "Guadalajara Intl", "Mexico"],
  ["MTY", "Monterrey", "Monterrey Intl", "Mexico"],
  ["SJD", "Los Cabos", "Los Cabos Intl", "Mexico"],
  ["PVR", "Puerto Vallarta", "Puerto Vallarta Intl", "Mexico"],
  ["PTY", "Panama City", "Tocumen Intl", "Panama"],
  ["SJO", "San José", "Juan Santamaría Intl", "Costa Rica"],
  ["HAV", "Havana", "José Martí Intl", "Cuba"],
  ["SJU", "San Juan", "Luis Muñoz Marín Intl", "Puerto Rico"],
  ["PUJ", "Punta Cana", "Punta Cana Intl", "Dominican Republic"],
  ["SDQ", "Santo Domingo", "Las Américas Intl", "Dominican Republic"],
  ["MBJ", "Montego Bay", "Sangster Intl", "Jamaica"],
  ["NAS", "Nassau", "Lynden Pindling Intl", "Bahamas"],
  // South America
  ["GRU", "São Paulo", "Guarulhos Intl", "Brazil"],
  ["GIG", "Rio de Janeiro", "Galeão Intl", "Brazil"],
  ["BSB", "Brasília", "Brasília Intl", "Brazil"],
  ["EZE", "Buenos Aires", "Ministro Pistarini (Ezeiza)", "Argentina"],
  ["AEP", "Buenos Aires", "Aeroparque Jorge Newbery", "Argentina"],
  ["SCL", "Santiago", "Arturo Merino Benítez Intl", "Chile"],
  ["BOG", "Bogotá", "El Dorado Intl", "Colombia"],
  ["MDE", "Medellín", "José María Córdova Intl", "Colombia"],
  ["LIM", "Lima", "Jorge Chávez Intl", "Peru"],
  ["UIO", "Quito", "Mariscal Sucre Intl", "Ecuador"],
  ["GYE", "Guayaquil", "José Joaquín de Olmedo Intl", "Ecuador"],
  ["CCS", "Caracas", "Simón Bolívar Intl", "Venezuela"],
  ["MVD", "Montevideo", "Carrasco Intl", "Uruguay"],
  ["LPB", "La Paz", "El Alto Intl", "Bolivia"],
  ["ASU", "Asunción", "Silvio Pettirossi Intl", "Paraguay"],
  // Europe — UK & Ireland
  ["LHR", "London", "Heathrow", "UK"],
  ["LGW", "London", "Gatwick", "UK"],
  ["STN", "London", "Stansted", "UK"],
  ["LTN", "London", "Luton", "UK"],
  ["LCY", "London", "London City", "UK"],
  ["MAN", "Manchester", "Manchester", "UK"],
  ["EDI", "Edinburgh", "Edinburgh", "UK"],
  ["BHX", "Birmingham", "Birmingham", "UK"],
  ["GLA", "Glasgow", "Glasgow", "UK"],
  ["DUB", "Dublin", "Dublin", "Ireland"],
  // Europe — Western
  ["CDG", "Paris", "Charles de Gaulle", "France"],
  ["ORY", "Paris", "Orly", "France"],
  ["NCE", "Nice", "Côte d'Azur", "France"],
  ["LYS", "Lyon", "Lyon–Saint-Exupéry", "France"],
  ["AMS", "Amsterdam", "Schiphol", "Netherlands"],
  ["FRA", "Frankfurt", "Frankfurt", "Germany"],
  ["MUC", "Munich", "Munich", "Germany"],
  ["BER", "Berlin", "Berlin Brandenburg", "Germany"],
  ["DUS", "Düsseldorf", "Düsseldorf", "Germany"],
  ["HAM", "Hamburg", "Hamburg", "Germany"],
  ["CGN", "Cologne", "Cologne Bonn", "Germany"],
  ["STR", "Stuttgart", "Stuttgart", "Germany"],
  ["BRU", "Brussels", "Brussels", "Belgium"],
  ["ZRH", "Zurich", "Zurich", "Switzerland"],
  ["GVA", "Geneva", "Geneva", "Switzerland"],
  ["VIE", "Vienna", "Vienna Intl", "Austria"],
  ["LUX", "Luxembourg", "Luxembourg", "Luxembourg"],
  // Europe — Southern
  ["MAD", "Madrid", "Adolfo Suárez Madrid–Barajas", "Spain"],
  ["BCN", "Barcelona", "Josep Tarradellas Barcelona–El Prat", "Spain"],
  ["AGP", "Málaga", "Málaga–Costa del Sol", "Spain"],
  ["PMI", "Palma", "Palma de Mallorca", "Spain"],
  ["VLC", "Valencia", "Valencia", "Spain"],
  ["FCO", "Rome", "Leonardo da Vinci–Fiumicino", "Italy"],
  ["MXP", "Milan", "Malpensa", "Italy"],
  ["LIN", "Milan", "Linate", "Italy"],
  ["BGY", "Milan", "Bergamo Orio al Serio", "Italy"],
  ["VCE", "Venice", "Marco Polo", "Italy"],
  ["NAP", "Naples", "Naples Intl", "Italy"],
  ["LIS", "Lisbon", "Humberto Delgado", "Portugal"],
  ["OPO", "Porto", "Francisco Sá Carneiro", "Portugal"],
  ["ATH", "Athens", "Eleftherios Venizelos", "Greece"],
  // Europe — Nordic
  ["CPH", "Copenhagen", "Copenhagen", "Denmark"],
  ["ARN", "Stockholm", "Arlanda", "Sweden"],
  ["OSL", "Oslo", "Gardermoen", "Norway"],
  ["HEL", "Helsinki", "Helsinki-Vantaa", "Finland"],
  ["KEF", "Reykjavík", "Keflavík", "Iceland"],
  // Europe — Central/Eastern & Turkey
  ["IST", "Istanbul", "Istanbul Airport", "Turkey"],
  ["SAW", "Istanbul", "Sabiha Gökçen", "Turkey"],
  ["AYT", "Antalya", "Antalya", "Turkey"],
  ["WAW", "Warsaw", "Chopin", "Poland"],
  ["KRK", "Kraków", "John Paul II", "Poland"],
  ["PRG", "Prague", "Václav Havel", "Czechia"],
  ["BUD", "Budapest", "Ferenc Liszt Intl", "Hungary"],
  ["OTP", "Bucharest", "Henri Coandă Intl", "Romania"],
  ["SOF", "Sofia", "Sofia", "Bulgaria"],
  ["ZAG", "Zagreb", "Franjo Tuđman", "Croatia"],
  ["BEG", "Belgrade", "Nikola Tesla", "Serbia"],
  ["RIX", "Riga", "Riga Intl", "Latvia"],
  ["TLL", "Tallinn", "Lennart Meri Tallinn", "Estonia"],
  ["VNO", "Vilnius", "Vilnius", "Lithuania"],
  ["SVO", "Moscow", "Sheremetyevo", "Russia"],
  ["DME", "Moscow", "Domodedovo", "Russia"],
  ["LED", "Saint Petersburg", "Pulkovo", "Russia"],
  ["KBP", "Kyiv", "Boryspil Intl", "Ukraine"],
  // Middle East
  ["DXB", "Dubai", "Dubai Intl", "UAE"],
  ["DWC", "Dubai", "Al Maktoum Intl", "UAE"],
  ["AUH", "Abu Dhabi", "Zayed Intl", "UAE"],
  ["DOH", "Doha", "Hamad Intl", "Qatar"],
  ["JED", "Jeddah", "King Abdulaziz Intl", "Saudi Arabia"],
  ["RUH", "Riyadh", "King Khalid Intl", "Saudi Arabia"],
  ["KWI", "Kuwait City", "Kuwait Intl", "Kuwait"],
  ["BAH", "Manama", "Bahrain Intl", "Bahrain"],
  ["MCT", "Muscat", "Muscat Intl", "Oman"],
  ["AMM", "Amman", "Queen Alia Intl", "Jordan"],
  ["BEY", "Beirut", "Rafic Hariri Intl", "Lebanon"],
  ["TLV", "Tel Aviv", "Ben Gurion", "Israel"],
  ["CAI", "Cairo", "Cairo Intl", "Egypt"],
  // Africa
  ["JNB", "Johannesburg", "O.R. Tambo Intl", "South Africa"],
  ["CPT", "Cape Town", "Cape Town Intl", "South Africa"],
  ["DUR", "Durban", "King Shaka Intl", "South Africa"],
  ["NBO", "Nairobi", "Jomo Kenyatta Intl", "Kenya"],
  ["ADD", "Addis Ababa", "Bole Intl", "Ethiopia"],
  ["LOS", "Lagos", "Murtala Muhammed Intl", "Nigeria"],
  ["ABV", "Abuja", "Nnamdi Azikiwe Intl", "Nigeria"],
  ["ACC", "Accra", "Kotoka Intl", "Ghana"],
  ["CMN", "Casablanca", "Mohammed V Intl", "Morocco"],
  ["RAK", "Marrakesh", "Marrakesh Menara", "Morocco"],
  ["TUN", "Tunis", "Tunis–Carthage", "Tunisia"],
  ["ALG", "Algiers", "Houari Boumediene", "Algeria"],
  ["DAR", "Dar es Salaam", "Julius Nyerere Intl", "Tanzania"],
  ["DKR", "Dakar", "Blaise Diagne Intl", "Senegal"],
  // Asia — East
  ["HND", "Tokyo", "Haneda", "Japan"],
  ["NRT", "Tokyo", "Narita Intl", "Japan"],
  ["KIX", "Osaka", "Kansai Intl", "Japan"],
  ["NGO", "Nagoya", "Chubu Centrair Intl", "Japan"],
  ["FUK", "Fukuoka", "Fukuoka", "Japan"],
  ["CTS", "Sapporo", "New Chitose", "Japan"],
  ["ICN", "Seoul", "Incheon Intl", "South Korea"],
  ["GMP", "Seoul", "Gimpo Intl", "South Korea"],
  ["PEK", "Beijing", "Beijing Capital Intl", "China"],
  ["PKX", "Beijing", "Beijing Daxing Intl", "China"],
  ["PVG", "Shanghai", "Pudong Intl", "China"],
  ["SHA", "Shanghai", "Hongqiao Intl", "China"],
  ["CAN", "Guangzhou", "Baiyun Intl", "China"],
  ["SZX", "Shenzhen", "Bao'an Intl", "China"],
  ["CTU", "Chengdu", "Tianfu Intl", "China"],
  ["CKG", "Chongqing", "Jiangbei Intl", "China"],
  ["XIY", "Xi'an", "Xianyang Intl", "China"],
  ["HGH", "Hangzhou", "Xiaoshan Intl", "China"],
  ["HKG", "Hong Kong", "Hong Kong Intl", "Hong Kong"],
  ["TPE", "Taipei", "Taoyuan Intl", "Taiwan"],
  ["MFM", "Macau", "Macau Intl", "Macau"],
  // Asia — Southeast
  ["SIN", "Singapore", "Changi", "Singapore"],
  ["KUL", "Kuala Lumpur", "Kuala Lumpur Intl", "Malaysia"],
  ["BKK", "Bangkok", "Suvarnabhumi", "Thailand"],
  ["DMK", "Bangkok", "Don Mueang Intl", "Thailand"],
  ["HKT", "Phuket", "Phuket Intl", "Thailand"],
  ["CGK", "Jakarta", "Soekarno–Hatta Intl", "Indonesia"],
  ["DPS", "Bali", "Ngurah Rai (Denpasar)", "Indonesia"],
  ["MNL", "Manila", "Ninoy Aquino Intl", "Philippines"],
  ["CEB", "Cebu", "Mactan–Cebu Intl", "Philippines"],
  ["SGN", "Ho Chi Minh City", "Tan Son Nhat Intl", "Vietnam"],
  ["HAN", "Hanoi", "Noi Bai Intl", "Vietnam"],
  ["PNH", "Phnom Penh", "Phnom Penh Intl", "Cambodia"],
  ["RGN", "Yangon", "Yangon Intl", "Myanmar"],
  // Asia — South & Central
  ["DEL", "Delhi", "Indira Gandhi Intl", "India"],
  ["BOM", "Mumbai", "Chhatrapati Shivaji Maharaj Intl", "India"],
  ["BLR", "Bengaluru", "Kempegowda Intl", "India"],
  ["MAA", "Chennai", "Chennai Intl", "India"],
  ["HYD", "Hyderabad", "Rajiv Gandhi Intl", "India"],
  ["CCU", "Kolkata", "Netaji Subhas Chandra Bose Intl", "India"],
  ["COK", "Kochi", "Cochin Intl", "India"],
  ["DAC", "Dhaka", "Hazrat Shahjalal Intl", "Bangladesh"],
  ["CMB", "Colombo", "Bandaranaike Intl", "Sri Lanka"],
  ["KTM", "Kathmandu", "Tribhuvan Intl", "Nepal"],
  ["ISB", "Islamabad", "Islamabad Intl", "Pakistan"],
  ["KHI", "Karachi", "Jinnah Intl", "Pakistan"],
  ["LHE", "Lahore", "Allama Iqbal Intl", "Pakistan"],
  ["TAS", "Tashkent", "Islam Karimov Tashkent Intl", "Uzbekistan"],
  ["ALA", "Almaty", "Almaty Intl", "Kazakhstan"],
  // Oceania
  ["SYD", "Sydney", "Kingsford Smith", "Australia"],
  ["MEL", "Melbourne", "Melbourne (Tullamarine)", "Australia"],
  ["BNE", "Brisbane", "Brisbane", "Australia"],
  ["PER", "Perth", "Perth", "Australia"],
  ["ADL", "Adelaide", "Adelaide", "Australia"],
  ["OOL", "Gold Coast", "Gold Coast", "Australia"],
  ["CNS", "Cairns", "Cairns", "Australia"],
  ["AKL", "Auckland", "Auckland", "New Zealand"],
  ["CHC", "Christchurch", "Christchurch", "New Zealand"],
  ["WLG", "Wellington", "Wellington", "New Zealand"],
  ["NAN", "Nadi", "Nadi Intl", "Fiji"],
  ["PPT", "Papeete", "Faa'a Intl", "French Polynesia"],
  ["GUM", "Hagåtña", "Antonio B. Won Pat Intl", "Guam"],
];

export const AIRPORTS: Airport[] = RAW.map(([iata, city, name, country]) => ({
  iata,
  city,
  name,
  country,
}));

/** Ranked type-ahead search over the embedded directory. */
export function searchAirports(query: string, limit = 8): Airport[] {
  const q = query.trim().toLowerCase();
  if (!q) return AIRPORTS.slice(0, limit);

  const scored: Array<{ a: Airport; s: number }> = [];
  for (const a of AIRPORTS) {
    const iata = a.iata.toLowerCase();
    const city = a.city.toLowerCase();
    const name = a.name.toLowerCase();
    const country = a.country.toLowerCase();
    let s = -1;
    if (iata === q) s = 0;
    else if (iata.startsWith(q)) s = 1;
    else if (city.startsWith(q)) s = 2;
    else if (city.includes(q)) s = 3;
    else if (name.toLowerCase().includes(q)) s = 4;
    else if (country.startsWith(q)) s = 5;
    if (s >= 0) scored.push({ a, s });
  }
  scored.sort((x, y) => x.s - y.s || x.a.city.localeCompare(y.a.city));
  return scored.slice(0, limit).map((x) => x.a);
}
